<<<<<<< HEAD
# Generated by Django 3.2.3 on 2021-05-20 02:33
=======
# Generated by Django 3.2.3 on 2021-05-16 09:50
>>>>>>> 609159725a8427956399f25bc6c3d39cc33898e1

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
<<<<<<< HEAD
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
=======
                ('timestamp', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
>>>>>>> 609159725a8427956399f25bc6c3d39cc33898e1
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
<<<<<<< HEAD
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
=======
                ('timestamp', models.DateTimeField()),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=100)),
>>>>>>> 609159725a8427956399f25bc6c3d39cc33898e1
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
<<<<<<< HEAD
                ('content', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_posts', to='myapp.category')),
=======
                ('published_at', models.DateTimeField()),
                ('description', models.TextField()),
                ('is_public', models.BooleanField()),
                ('title', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_posts', to='myapp.category')),
>>>>>>> 609159725a8427956399f25bc6c3d39cc33898e1
                ('tags', models.ManyToManyField(to='myapp.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
<<<<<<< HEAD
                ('binary', models.BinaryField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/images/')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.post')),
=======
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('binary', models.BinaryField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='upload/images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.post')),
>>>>>>> 609159725a8427956399f25bc6c3d39cc33898e1
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
<<<<<<< HEAD
                ('binary', models.BinaryField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='upload/files/')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.post')),
=======
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='upload/files/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('binary', models.BinaryField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.post')),
>>>>>>> 609159725a8427956399f25bc6c3d39cc33898e1
            ],
        ),
    ]
